dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
dat$Time <- strptime(dat$Time, "%H:%M:%S")
dat$Date <- as.Date(dat$Date, format = "%d/%m/%Y")
tidydat <- subset(dat, dat$Date == "2007-02-01" | dat$Date == "2007-02-02")
hist(tidydat$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot1.png")
dev.off()